### ISSUE TITLE
Upgrade RAM and CPU- Prohance Server (192.168.25.63)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Server#17]
Need to Upgarde RAM (8GB tom 12 GB) and CPU (2 core to 4 core) for installation Prohance Server.

@Isgec/dc-infra-team , Myself Praveen and Mr. MS is for same.

**Comment by msrawat-isgec** [comment]
Praveen Ji Same has been done.

 

Regards

M.S.Rawat
