### ISSUE TITLE
Database restroation and configuation in 192.168.25.25. Server at sector-63 Location

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#19]
Database restroation and configuation in 192.168.25.25. Server at sector-63 Location
@vinay-isgec

**Comment by msrawat-isgec** [comment]
@Isgec/dc-infra-team

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by praveen-isgec** [comment]
Db Server has been restored and tested working fine

 

 

Regards

M.s.Rawat 

 

From: Deepak Rawat [mailto:deepak.rawat@pathinfotech.com] 
Sent: Thursday, February 04, 2021 2:32 PM
To: Vmanageit; sqldba
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal; DCADMIN
Subject: Re: MS SQL Database Server Restarting/Isgec/Call id 13

 

Dear All,

 

Call as been acknowledged, We are working on it.

 

Regards,

Deepak Rawat

  _____  

From: Vmanageit <vmanageit@pathinfotech.com>
Sent: 04 February 2021 13:58
To: sqldba <sqldba@pathinfotech.com>; Deepak Rawat <deepak.rawat@pathinfotech.com>
Cc: dhirendra.singh@isgec.co.in <dhirendra.singh@isgec.co.in>; Vikram Bansal <vikram.bansal@pathinfotech.com>; DCADMIN <dcadmin@isgec.co.in>
Subject: RE: MS SQL Database Server Restarting/Isgec/Call id 13 

 

Hi Deepak,

 

Please have call id and do the needful.

 

Please ignore the previous mail

 

Best Regards,

Abhinay

Executive-vManageIT Help Desk |  <https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.pathinfotech.com%2f&c=E,1,G3b7TbGChsoJ2grK5hxszdy649jgQf2yLAI9U4Nd_VGRrDIRim6pBga7G_z1vq0aIqbyQxkAvJzAvtMxFWFTqR5-9DFt_-MT1I4zcrzSbm1DOO0E0esG4ivlQw,,&typo=1> Path Infotech Limited

E-1, Sec 63, Noida – 201301, India | (T) +91- <callto:+1120-4726> 120-4726 100/ (Ext.) 199/198

(M) +91 8860270088

Follow Us:  <https://linkedin.com/company/path-infotech-ltd> LinkedIn |  <https://twitter.com/PathInfotechLtd> Twitter |  <https://www.facebook.com/PathInfotechLtd> Facebook |  <https://www.youtube.com/c/PathInfotechLtdNoida> YouTube

Pl. share your valuable feedback at  <mailto:dba.feedback@pathinfotech.com> dba.feedback@pathinfotech.com

 

From: DCADMIN <dcadmin@isgec.co.in> 
Sent: Thursday, February 4, 2021 12:33 PM
To: Vmanageit <vmanageit@pathinfotech.com>
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal <vikram.bansal@pathinfotech.com>
Subject: MS SQL Database Server Restarting

 

Dear Team,

 

Please log a call for MS SQL Database Server  ( ERP DB Server-1192.9.200.129  )  call raise on incident purpose  & urgent basis.

 

Regards

M.S.Rawat

 

 

 

From: Vmanageit [mailto:vmanageit@pathinfotech.com] 
Sent: Thursday, February 04, 2021 12:45 PM
To: Chandan Singh2; sqldba
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal; DCADMIN
Subject: RE: MS SQL Database Server Restarting/Isgec/Call id 133

 

Hi Chandan,

 

Please have call id.

 

Best Regards,

Abhinay

Executive-vManageIT Help Desk |  <https://linkprotect.cudasvc.com/url?a=http%3a%2f%2fwww.pathinfotech.com%2f&c=E,1,o8ML3JN0d-kFXCiNH1czz_gdfZ4VFLvu1iIdRrOFjOsUDlTo5AsqEb6E_RUeQcot4-tMDg25PzRZWaSafFRhgIDzI24CZ4NS6ib2230xugRlo9-BtiuxII-v&typo=1> Path Infotech Limited

E-1, Sec 63, Noida – 201301, India | (T) +91- <callto:+1120-4726> 120-4726 100/ (Ext.) 199/198

(M) +91 8860270088

Follow Us:  <https://linkedin.com/company/path-infotech-ltd> LinkedIn |  <https://twitter.com/PathInfotechLtd> Twitter |  <https://www.facebook.com/PathInfotechLtd> Facebook |  <https://www.youtube.com/c/PathInfotechLtdNoida> YouTube

Pl. share your valuable feedback at  <mailto:dba.feedback@pathinfotech.com> dba.feedback@pathinfotech.com

 

 

From: DCADMIN <dcadmin@isgec.co.in> 
Sent: Thursday, February 4, 2021 12:33 PM
To: Vmanageit <vmanageit@pathinfotech.com>
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal <vikram.bansal@pathinfotech.com>
Subject: MS SQL Database Server Restarting

 

Dear Team,

 

Please log a call for MS SQL Database Server  ( ERP DB Server-1192.9.200.129  )  call raise on incident purpose  & urgent basis.

 

Regards

M.S.Rawat

 

 

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: Thursday, February 04, 2021 3:43 PM
To: 'DCADMIN'
Cc: 'Team mention'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'
Subject: RE: [Isgec/ITIL-Server] Database restroation and configuation in 192.168.25.25. Server at sector-63 Location (#19)

 

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785
