### ISSUE TITLE
Restored Database on 192.9.200.45 Server from 192.9.200.192.9.200.129 , 2Feb2021 Database backup

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#20]
Restored Database on 192.9.200.45 Server from 192.9.200.192.9.200.129 , 2Feb2021 Database backup
@Isgec/dc-infra-team

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by msrawat-isgec** [comment]
call to pathe db admin and discussed about the restoration

**Comment by msrawat-isgec** [comment]
![Uploading image.png…]()

**Comment by msrawat-isgec** [comment]
![Uploading image.png…]()

**Comment by msrawat-isgec** [comment]
now database restroed upto 3Feb2021
![image](https://user-images.githubusercontent.com/57947631/106887557-54351c00-670b-11eb-83bb-dd8fd84dabfa.png)
