### ISSUE TITLE
New Aruba Server Creating Request By Vinay Sir, Server Name- Airwave-ISGEC-192.9.200.144

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#23]
New Aruba Server Creating Request By Vinay Sir, Server Name- Airwave-ISGEC-192.9.200.144

Request :-1: 
![image](https://user-images.githubusercontent.com/57947631/107202407-2cea9180-6a20-11eb-8a41-7b89808cc274.png)

**Comment by msrawat-isgec** [comment]
now new Aruba Server now creating with HP With Dinesh Comnet.

@Isgec/dc-infra-team @praveen-isgec @msrawat-isgec

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

AS discussed , we have created the New  Airwave Server in VM Host.

 

Details are Below.

 

IP Address : 192.9.200.144

Name : Airwave-ISGEC-192.9.200.144

Operating System : Centos – 7  (AMP-8.2.11.2-x86_64)

Disk Space:      160 GB

CPU:                6Vcpu

Memory:         8GB

 

 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

AS discussed , we have created the New  Airwave Server in VM Host.

 

Details are Below.

 

IP Address : 192.9.200.144

Name : Airwave-ISGEC-192.9.200.144

Operating System : Centos – 7  (AMP-8.2.11.2-x86_64)

Disk Space:      150 GB

CPU:                6Vcpu

Memory:         8GB

 

 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

As Requested By Vinay Sir, The Airwave-ISGEC-192.9.200.144 , we have Increased 16GM Memory to 20GB.

 

FTI… Only Sir.. 

 



 



Regards

M.S.Rawat 

 

From: DCADMIN ***@***.*** 
Sent: Monday, February 08, 2021 3:45 PM
To: ***@***.***
Cc: 'Mention'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'; 'Dinesh Chauhan' ***@***.***)
Subject: RE: New Aruba Server Creating Request By Vinay Sir, Server Name- Airwave-ISGEC-192.9.200.144 (#23)

 

Dear Sir,

 

AS discussed , we have created the New  Airwave Server in VM Host.

 

Details are Below.

 

IP Address : 192.9.200.144

Name : Airwave-ISGEC-192.9.200.144

Operating System : Centos – 7  (AMP-8.2.11.2-x86_64)

Disk Space:      150 GB

CPU:                6Vcpu

Memory:         8GB

 

 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
Have you shutdown old Airwave server or it still ON ?

 

 

From: DCADMIN ***@***.***> 
Sent: 12 April 2021 12:03
To: ***@***.***
Cc: 'Mention' ***@***.***>; ***@***.***; 'Isgec/ITIL-Server' ***@***.***>; 'Isgec/ITIL-Server' ***@***.***>; 'Isgec/ITIL-Server' ***@***.***>; ''Dinesh Chauhan'' ***@***.***>
Subject: RE: New Aruba Server Creating Request By Vinay Sir, Server Name- Airwave-ISGEC-192.9.200.144 (#23)

 

Dear Sir,

 

As Requested By Vinay Sir, The Airwave-ISGEC-192.9.200.144 , we have Increased 16GM Memory to 20GB.

 

FTI… Only Sir.. 

 



 



Regards

M.S.Rawat 

 

From: DCADMIN ***@***.*** 
Sent: Monday, February 08, 2021 3:45 PM
To: ***@***.*** ***@***.***> 
Cc: 'Mention'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'; 'Dinesh Chauhan' ***@***.*** ***@***.***> )
Subject: RE: New Aruba Server Creating Request By Vinay Sir, Server Name- Airwave-ISGEC-192.9.200.144 (#23)

 

Dear Sir,

 

AS discussed , we have created the New  Airwave Server in VM Host.

 

Details are Below.

 

IP Address : 192.9.200.144

Name : Airwave-ISGEC-192.9.200.144

Operating System : Centos – 7  (AMP-8.2.11.2-x86_64)

Disk Space:      150 GB

CPU:                6Vcpu

Memory:         8GB

 

 

Regards

M.S.Rawat
