### ISSUE TITLE
Database Server - Ganesha - 192.9.200.129 is working Slow request by Veena Mam.

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#24]
Database Server - Ganesha - 192.9.200.129 is working Slow request by Veena Mam.
@Isgec/dc-infra-team @praveen-isgec

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

We have call to Path – DB Admin checked and resolved the issue.

 

 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
Dear Sir,

 

Confirmed by Pankaj Gupta now working fine.

 

 

Case Logged case details :-


Your call has been registered with us. 

Call No. : 14
Call Date : 08-Feb-2021 18:31:28
Severity : Severity 4
Expected Resolution Date : 
Call Detail : MS SQL Database Server Restarting

With Regards, 
Helpdesk 

 

 

Regards

M.S.Rawat 

 

From: DCADMIN [mailto:dcadmin@isgec.co.in] 
Sent: Monday, February 08, 2021 6:31 PM
To: dhirendra.singh@isgec.co.in
Cc: 'Author'; 'Isgec/ITIL-Server'; 'Isgec/ITIL-Server'
Subject: RE: [Isgec/ITIL-Server] Database Server - Ganesha - 192.9.200.129 is working Slow request by Veena Mam. (#24)

 

Dear Sir,

 

We have call to Path – DB Admin checked and resolved the issue.

 

 

Regards

M.S.Rawat

**Comment by msrawat-isgec** [comment]
problem has resolved .
To	From	Subject	Received	Size	
Deepak Rawat; sqldba	Vmanageit	RE: MS SQL Database Server Restarting/ISGEC/Call id 134	7:13 PM	34 KB	
dhirendra.singh@isgec.co.in; DCADMIN	Vikram Bansal	RE: MS SQL Database Server Restarting/ISGEC/Call id 14	6:58 PM	29 KB	
Vmanageit; sqldba	Deepak Rawat	RE: MS SQL Database Server Restarting/ISGEC/Call id 14	6:55 PM	26 KB
