### ISSUE TITLE
IMAP port 143-Mail Migration testing with office365 from 224 server

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-Server#27]
Dear Team,

as per Microsoft it required 143 port in case of non encrypted connection. we want to test mail migration from our mail server to office365 with at least 100 gb data transfer to calculate the time taken to plan for mail migration.

Port needs to be mapped with mobile01.isgec.co.in with allowed only username. @Isgec/dc-infra-team @vinay-isgec 

Kindly allow additional port on keeping existing setting intact ( used by others users on mobile.)

![migaration endpoint](https://user-images.githubusercontent.com/49862746/108020212-e4dff600-7041-11eb-8e9b-59e8d27d9da0.JPG)

**Comment by vinay-isgec** [comment]
Dear Team,

 

Required port added with policy in fortigate  firewall 192.168.25.12.

 

Please check and confirm 

 

Regards

Vinay

**Comment by isgecit** [comment]
Tested Working fine.
