### ISSUE TITLE
Database Monthly Proactive Health Checkup. of All DB Server 

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#31]
Database Monthly Proactive Health Checkup. of All DB Server .
@isgecit @msrawat-isgec

**Comment by msrawat-isgec** [comment]
@msrawat-isgec @Isgec/dc-infra-team 
Database Health checkup scheduled .


From: Vmanageit [mailto:vmanageit@pathinfotech.com] 
Sent: Thursday, February 25, 2021 4:15 PM
To: DCADMIN; Deepak Rawat
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal
Subject: RE: Proactive MS- SQL Database Health Checkup/ISGEC/S3/REQ/Call ID-0136

Dear Sir,
 
As per email trail confirmation, we are scheduling our engineer tomorrow 26th Feb’21 for MS-SQL database health check activity.
 
@Deepak Rawat As discussed, Please fulfill this activity as per scheduled.

Best Regards,
Kapil Taneja
Senior Executive-vManageIT Help Desk | Path Infotech Limited
E-1, Sec 63, Noida – 201301, India | (T) +91-120-4726 100/ (Ext.) 199/198
(M) +91 72177 31726
Follow Us: LinkedIn | Twitter | Facebook | YouTube
Pl. share your valuable feedback at dba.feedback@pathinfotech.com 

From: DCADMIN <dcadmin@isgec.co.in> 
Sent: Thursday, February 25, 2021 2:21 PM
To: Vmanageit <vmanageit@pathinfotech.com>
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal <vikram.bansal@pathinfotech.com>; Deepak Rawat <deepak.rawat@pathinfotech.com>
Subject: RE: Proactive MS- SQL Database Health Checkup

Dear Atinder Jeet Singh,

Please aligned and confirm the same

Regards
M.S.Rawat
From: Vmanageit [mailto:vmanageit@pathinfotech.com] 
Sent: Wednesday, February 24, 2021 1:10 PM
To: DCADMIN
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal; Deepak Rawat
Subject: RE: Proactive MS- SQL Database Health Checkup

Dear Sir,

Request you to please confirm your availability for 26th Feb’21 (Friday) to schedule this activity. so that we can align engineer remotely.

Best Regards,
Atinder Jeet Singh
Executive- vManageIT Help Desk | Path Infotech Limited
E-1, Sec 63, Noida – 201301, India | (T) +91-120-4726 100/ (Ext.) 199/198
(M) +91 9818985226
Follow Us: LinkedIn | Twitter | Facebook | YouTube

From: DCADMIN <dcadmin@isgec.co.in> 
Sent: Wednesday, February 24, 2021 12:49 PM
To: Vmanageit <vmanageit@pathinfotech.com>
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal <vikram.bansal@pathinfotech.com>; Deepak Rawat <deepak.rawat@pathinfotech.com>
Subject: RE: Proactive MS- SQL Database Health Checkup

Dear Team,

proactive ,  Monthly DB Health Checkup is pending, please confirm when will be scheduled .

Regards
M.S.Rawat

From: DCADMIN [mailto:dcadmin@isgec.co.in] 
Sent: Tuesday, February 09, 2021 11:55 AM
To: Vmanageit (vmanageit@pathinfotech.com)
Cc: dhirendra.singh@isgec.co.in; Vikram Bansal (vikram.bansal@pathinfotech.com); Deepak Rawat (deepak.rawat@pathinfotech.com)
Subject: Proactive MS- SQL Database Health Checkup

Dear Team, 

Please make the schedule for proactive ,  Monthly DB Health Checkup on 10th Feb-2021 .

And confirm the aligned Engineer for the same. 


Regards
M.S.Rawat

**Comment by msrawat-isgec** [comment]
@msrawat-isgec @Isgec/dc-infra-team 
Give RDP to Path DB Admin and Health checkup is going on.

consulting \| learning \| outsourcing \|technology |   |   |   |  
-- | -- | -- | -- | --
 
  |

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785
