### ISSUE TITLE
EXSi 6.0 install in OLD JV Server

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Server#37]
VMware-ESXi-6.0.0 installation in Old JV Server.

@Isgec/dc-infra-team  , Myself Praveen and MS Ji and Vinay Sir are working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: Wednesday, March 10, 2021 10:00 AM
To: Isgec/ITIL-Server
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Server] EXSi 6.0 install in OLD JV Server (#37)

 

VMware-ESXi-6.0.0 installation in Old JV Server.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen and MS Ji and Vinay Sir are working for the same.
