### ISSUE TITLE
Mail Piler 5 - Creation & testing of Mail Piler 5 

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-Server#4]
Mail Piler 5 Needs to be created at our mail piler 4 is having 115 gb space only.
@Isgec/dc-infra-team please provide another VM machine with storage atleast 3 tb to keep 1 year minimum archive.

**Comment by dhirendra-isgec** [comment]
What is the current total storage occupied by complete mailing system

**Comment by dhirendra-isgec** [comment]
What is the current capacity used by mailing system? 

4 TB ISSCI space given to mail for testing VMs environment that need to be free for Archival 

 

Dhirendra

**Comment by bhupender-isgec** [comment]
Dear Praveen Ji,

 

Please remove/disable  iqn InitiatorName=iqn.1994-05.com.redhat:62cd5a399d36 which is attached with IP 192.168.9.216  this is approx. 5 tb space which was used for backup prior.

Once removed/disabled we will keep it under observation till tomorrow evening.

 

Current capacity I will calculate & share.

 

Thanks

Bhupender K Kashyap

**Comment by praveen-isgec** [comment]
This is NetApp04 storage LUN (iqn.1994-05.com.redhat:62cd5a399d36) , Now i disable on storage. Tomorrow i will be delete it.

**Comment by dhirendra-isgec** [comment]
Pl take action as per schedule. 

Bhupender confirm to Praveen

**Comment by bhupender-isgec** [comment]
Duplicate case was opened by MS . Already updated . Piler5 is live 

@dhirendra-isgec  Please close this case.
