### ISSUE TITLE
Server drive for databackup mount in ADC Sec-63 for VM (192.168.25.110) local Storage

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Server#45]
Need to mount 1TB drive on ADC Sec-63 (192.168.25.53) from VM (192.168.25.10) local storage.

 We will move data form live file server to this drive and users will access this data Read Only for reference and we will grow capacity in future as per requirement.

Dhirendra Sir, Kindly approve.

@Isgec/dc-infra-team   , Myself and Mr. MS ji working for the same.

**Comment by msrawat-isgec** [comment]
FYI.

 

 

 

From: praveen-isgec ***@***.*** 
Sent: 25 March 2021 11:04
To: Isgec/ITIL-Server
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Server] Server drive for databackup mount in ADC Sec-63 for VM (192.168.25.110) local Storage (#45)

 

Need to mount 1TB drive on ADC Sec-63 (192.168.25.53) from VM (192.168.25.10) local storage.

We will move data form live file server to this drive and users will access this data Read Only for reference and we will grow capacity in future as per requirement.

Dhirendra Sir, Kindly approve.

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself and Mr. MS ji working for the same.

**Comment by dhirendra-isgec** [comment]
Ok approved

**Comment by msrawat-isgec** [comment]
Now 1TB Disk Drive has been created .from Local StorageR5-192.168.25.110 

 

Praveen ji please check and confirm .

 

 

 

Regards

M.S.Rawat
