### ISSUE TITLE
SR: 1055673633 |Service Tag: C4J5T02 | E1000 Failsafe error, AnsyFileServer not Powering ON

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-Server#46]
Dell PowerEdge R910 , AnsysFileServer is not powering on since todayu morning.
I checked E1000 Failsafe voltage error is showing on LED display.
Thank you for your time on call. We have dispatched the suspected Hardware along with an Engineer and should be addressed at the earliest within 4 hours. The dispatch number is 84417290049. You will get further update from our service team to fix the ETA shortly.
Regards,
Parvez Ahmed
Enterprise Pro-SupportPlus Engineer

Now case is generated in Dell Support to resolve the issue, they check and found the Hardware multi component failure issue.
@Isgec/dc-infra-team   ,Myself Praveen Kumar and Mr. MS Ji  are working wth Dell Support for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: 30 March 2021 14:31
To: Isgec/ITIL-Server
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-Server] SR: 1055673633 |Service Tag: C4J5T02 | E1000 Failsafe error, AnsyFileServer not Powering ON (#46)

 

Dell PowerEdge R910 , AnsysFileServer is not powering on since todayu morning.
I checked E1000 Failsafe voltage error is showing on LED display.
Thank you for your time on call. We have dispatched the suspected Hardware along with an Engineer and should be addressed at the earliest within 4 hours. The dispatch number is 84417290049. You will get further update from our service team to fix the ETA shortly.
Regards,
Parvez Ahmed
Enterprise Pro-SupportPlus Engineer

Now case is generated in Dell Support to resolve the issue, they check and found the Hardware multi component failure issue.
@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  ,Myself Praveen Kumar and Mr. MS Ji are working wth Dell Support for the same.

**Comment by msrawat-isgec** [comment]
Hi Mr. Ramnivas,

 

Please find the Address details for replaced the part.

 

ISGEC Heavy Engineering ltd.

A-7, Srector-63

Noida - 201301

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: DCADMIN ***@***.***> 
Sent: 30 March 2021 14:19
To: 'Praveen' ***@***.***>
Cc: ***@***.***; ***@***.***
Subject: FW: Engg details SER#84417290049

 

 

 

From: ***@***.*** ***@***.***>
***@***.*** 
Sent: 30 March 2021 13:57
To: ***@***.*** ***@***.***> 
Cc: ***@***.*** ***@***.***> ; ***@***.***
***@***.***> ; ***@***.***
***@***.***> 
Subject: Engg details SER#84417290049

 

Hi Team,

 

Kindly find the below Engg details for gatepass. 

 

Engg :  Ramnivas Dwivedi

Contact : 88827 15543 / 9205258535

Carry : Tool Kit , Pen Drive , CD & Cell Phone

 

Backup Engg: ARJUN AWASTHI

Contact: 9654613272

Carry : Tool kit bag, Pen drives, CD & Cell phone.

 

Regards,

Syed Mathin

Dell Service Provider

0821-4011083 | 0821-4011082 | 9741256043

'The information contained in this electronic message and any attachments to
this message are intended for the exclusive use of the addressee(s) and may
contain proprietary, confidential or privileged information. If you are not
the intended recipient, you should not disseminate, distribute or copy this
e-mail. Please notify the sender immediately and destroy all copies of this
message and any attachments. WARNING: Computer viruses can be transmitted
via email. The recipient should check this email and any attachments for the
presence of viruses. The company accepts no liability for any damage caused
by any virus transmitted by this email. www.wipro.com
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fwww.wipro.com&c=E,1,gDy
Xfs1cZ88sJkhKriJr7oEWTukxoo1PnUApXlVX5GqFCAiMIT7G3A84Qndz0bBCsRWWABZXhlCvaw7
BGJyCySpyWYLlkq6rAv-lU0Ob50qibl-RRtBpmQ,,&typo=1&ancr_add=1> '

**Comment by msrawat-isgec** [comment]
Hi Team,

 

Please find the DSET Report enclosed herewith.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Praveen Kumar ***@***.***> 
Sent: 30 March 2021 15:14
To: ***@***.***' ***@***.***>
Cc: ***@***.***' ***@***.***>;
***@***.***' ***@***.***>;
***@***.***'
***@***.***>;
'DCADMIN' ***@***.***>; ***@***.***'
***@***.***>; ***@***.***'
***@***.***>; 'DCADMIN' ***@***.***>;
***@***.***' ***@***.***>; ***@***.***'
***@***.***>
Subject: RE: Engg details SER#84417290049

 

Hi Mr. Ramnivas,

 

Please find the Address details for replaced the part.

 

ISGEC Heavy Engineering ltd.

A-7, Srector-63

Noida - 201301

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: DCADMIN ***@***.*** ***@***.***> > 
Sent: 30 March 2021 14:19
To: 'Praveen' ***@***.***
***@***.***> >
Cc: ***@***.*** ***@***.***> ;
***@***.*** ***@***.***> 
Subject: FW: Engg details SER#84417290049

 

 

 

From: ***@***.*** ***@***.***>
***@***.*** 
Sent: 30 March 2021 13:57
To: ***@***.*** ***@***.***> 
Cc: ***@***.*** ***@***.***> ; ***@***.***
***@***.***> ; ***@***.***
***@***.***> 
Subject: Engg details SER#84417290049

 

Hi Team,

 

Kindly find the below Engg details for gatepass. 

 

Engg :  Ramnivas Dwivedi

Contact : 88827 15543 / 9205258535

Carry : Tool Kit , Pen Drive , CD & Cell Phone

 

Backup Engg: ARJUN AWASTHI

Contact: 9654613272

Carry : Tool kit bag, Pen drives, CD & Cell phone.

 

Regards,

Syed Mathin

Dell Service Provider

0821-4011083 | 0821-4011082 | 9741256043

'The information contained in this electronic message and any attachments to
this message are intended for the exclusive use of the addressee(s) and may
contain proprietary, confidential or privileged information. If you are not
the intended recipient, you should not disseminate, distribute or copy this
e-mail. Please notify the sender immediately and destroy all copies of this
message and any attachments. WARNING: Computer viruses can be transmitted
via email. The recipient should check this email and any attachments for the
presence of viruses. The company accepts no liability for any damage caused
by any virus transmitted by this email. www.wipro.com
<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fwww.wipro.com&c=E,1,gDy
Xfs1cZ88sJkhKriJr7oEWTukxoo1PnUApXlVX5GqFCAiMIT7G3A84Qndz0bBCsRWWABZXhlCvaw7
BGJyCySpyWYLlkq6rAv-lU0Ob50qibl-RRtBpmQ,,&typo=1&ancr_add=1> '
