### ISSUE TITLE
Barrackuda Server  OVF installation - IP 192.9.200.217

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#51]
Barrackuda Server  OVF installation - IP 192.9.200.217
and configured with Bhupender

**Comment by msrawat-isgec** [comment]
Checked Through Web is  Working fine.
![image](https://user-images.githubusercontent.com/57947631/118645093-20828b80-b7fc-11eb-9e6d-cacd378bf849.png)

**Comment by bhupender-isgec** [comment]
@dhirendra-isgec  for review & closure pls

**Comment by bhupender-isgec** [comment]
Barracuda Device received & Installed along with configuration. Working fine. VM Barracuda shutdown done before making barracuda hardware live.
@msrawat-isgec  - do  not start Barracuda VM which was installed two days back. 
@dhirendra-isgec   - Please review & close.

**Comment by dhirendra-isgec** [comment]
Okay, change the contact details in barracuda portal
