### ISSUE TITLE
Submitted log of mobile01.isgec.co.in for security analysis

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-Server#52]
@hariharan-isgec  for your analysis please.

[maillog.zip](https://github.com/Isgec/ITIL-Server/files/6513642/maillog.zip)

**Comment by hariharan-isgec** [comment]
Log for the period 16th May 2021 to 20th May 2021 is being Analysed

**Comment by hariharan-isgec** [comment]
Observed that the System has blocked vipink's login as he is not anymore with Isgec 
**May 16 11:21:45 mailproxy dovecot: imap-login: Aborted login (proxy dest auth failed): user=<vipink@ijt.co.in>, method=PLAIN, rip=192.168.25.12, lip=192.9.200.218, session=<BlQkEmzCat/AqBkM>**

**Comment by hariharan-isgec** [comment]
No malicious activity detected
**Log Analysis complete**
