### ISSUE TITLE
New Perk Server - 192.9.200.146 very Lows Disk Space

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#53]
New Perk Server - 192.9.200.146 very Lows Disk Space
@Isgec/dc-infra-team

**Comment by msrawat-isgec** [comment]
Disk Space is very low and details are below.
![image](https://user-images.githubusercontent.com/57947631/119490579-9fd30a80-bd7a-11eb-9d1b-0e898414ff68.png)

**Comment by msrawat-isgec** [comment]
Now we are discussed with dhirender sir New  LUN is creating in HP 3 Par

**Comment by praveen-isgec** [comment]
If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by praveen-isgec** [comment]
Dear Praveen Ji,

 

As discussed, Praveen Ji Please Create 1.5 TB LUN for New Perk Server -
192.9.200.146

 

 

 

Regards

M.S.Rawat 

 

From: DCADMIN ***@***.*** 
Sent: Monday, May 24, 2021 11:15 AM
To: ***@***.***'
Cc: ***@***.***'; 'Praveen'; ''Bhupender K Kashyap'';
***@***.***'
Subject: New Perk Server (PERK01) 192.9.200.146., C:> Drive disk Space
Availability 50.2GB & D:> Drive disk Space Availability 6.80GB F:> 5.40GB..

 

Dear Sir,

 

Checked the  New Perk Server (PERK01) 192.9.200.146., C:> Drive disk Space
Availability 50.2GB  & D:> Drive disk Space Availability  6.80GB  F:>
5.40GB..

 

 

Low disk space in D:> Drive disk Space Availability  6.80GB  F:>
5.40GB......

 

 

 



 

 

Regard.

M.S.Rawat

**Comment by praveen-isgec** [comment]
1.5 TB Lun is created on HP 3PAR  Storage from NL Space and exported to 192.9.200.186 VM Mashine.

**Comment by praveen-isgec** [comment]
Dear Mr. MS,

 

1.5 TB Lun is created from NL Space on HP 3PAR Storage and exported to
192.9.200.146 Host for Perk01 Server (192.9.200.146).

 

Please check and confirm.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: DCADMIN ***@***.***> 
Sent: 25 May 2021 17:34
To: ''Praveen'' ***@***.***>
Cc: ***@***.***; ***@***.***; 'Praveen'
***@***.***>; 'Isgec/ITIL-Server'
***@***.***>
Subject: Please Creat 1.5 TB LUN for New Perk Server - 192.9.200.146

 

Dear Praveen Ji,

 

As discussed, Praveen Ji Please Create 1.5 TB LUN for New Perk Server -
192.9.200.146

 

 

 

Regards

M.S.Rawat 

 

From: DCADMIN ***@***.*** 
Sent: Monday, May 24, 2021 11:15 AM
To: ***@***.***'
Cc: ***@***.***'; 'Praveen'; ''Bhupender K Kashyap'';
***@***.***'
Subject: New Perk Server (PERK01) 192.9.200.146., C:> Drive disk Space
Availability 50.2GB & D:> Drive disk Space Availability 6.80GB F:> 5.40GB..

 

Dear Sir,

 

Checked the  New Perk Server (PERK01) 192.9.200.146., C:> Drive disk Space
Availability 50.2GB  & D:> Drive disk Space Availability  6.80GB  F:>
5.40GB..

 

 

Low disk space in D:> Drive disk Space Availability  6.80GB  F:>
5.40GB......

 

 

 



 

 

Regard.

M.S.Rawat

**Comment by msrawat-isgec** [comment]
1.5 TB Maapted to 192.9.200.146 perk server.
![image](https://user-images.githubusercontent.com/57947631/119497360-19222b80-bd82-11eb-8424-09700b3c860e.png)

**Comment by msrawat-isgec** [comment]
![image](https://user-images.githubusercontent.com/57947631/119505512-aa959b80-bd8a-11eb-826c-e8f5ae9a87e4.png)

**Comment by msrawat-isgec** [comment]
As discussed today 26May2021 extended the LUN 1.5 to 2.5 TB.
![image](https://user-images.githubusercontent.com/57947631/119641072-e5eda400-be36-11eb-8270-2f6ae71c26d0.png)
