### ISSUE TITLE
DataCentre Multiple service failure alert on 9th June 2021

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-Server#55]
Multiple alert received from nagios. checked & found all network switch installed for server & storage is faulty.
secondly UPS-B is not giving backup

@Isgec/dc-infra-team @dhirendra-isgec @bhupender-isgec

**Comment by vinay-isgec** [comment]
one L-3 switch got damage due to UPS B  issue in data centre
Switch replaced and tested working fine

**Comment by vinay-isgec** [comment]
10-06-2021
bhupendra & myself reached at sec-24 office @ 7:30, replaced damage switched , after replaced switched netapp services also restored.
in UPS -B found 2 battery  open, vendor replaced  battery  from old keeping battery  stock, its under observation. 
asked vendor for send quotation 
@Isgec/dc-infra-team

**Comment by dhirendra-isgec** [comment]
Also add ILO lan connectivity from other switch
