### ISSUE TITLE
Nagios Server Reboot Required - Serial Port not detecting - connected with GSM modem

### ISSUE THREAD

**Issue by bhupender-isgec** [Isgec/ITIL-Server#6]
Nagios Server Reboot Required - Serial Port not detecting  which is used to connect with GSM modem. 
@Isgec/dc-infra-team  Please respond
@bhupender-isgec  for further action

**Comment by msrawat-isgec** [comment]
Deue to Console is disabled

 



 

 

M.S.Rwat

**Comment by msrawat-isgec** [comment]
Now Restarted the Nagios server .

 



 



Regards 

M.S.Rawat

**Comment by isgecit** [comment]
Tested & GSM modem working fine . SMS alert generating
