### ISSUE TITLE
New Mail Piler Server Creation Request By Bhupender ji

### ISSUE THREAD

**Issue by msrawat-isgec** [Isgec/ITIL-Server#8]
New Mail Piler Server Creation Request By Bhupender ji
@Isgec/dc-infra-team @msrawat-isgec @bhupender-isgec

**Comment by praveen-isgec** [comment]
As discussed, 3.2TB lun is created and assigned to VM through FC.
@msrawat-isgec , Please check on VM and do the needful accordingly.
@Isgec/dc-infra-team

**Comment by msrawat-isgec** [comment]
New Mail Piler Server has created - MailPiler5- 192.9.200.194 and moved to 3.20 Tm MailPIler5 LUN
confirm to bhupernder ji

**Comment by bhupender-isgec** [comment]
Piler -5 Configured  - drive mounted , Piler testing underway keeping. 

Mail testing happen yesterday late night with test emails being recorded. Server is under testing phase.

 

Thanks

Bhupender K Kashyap

**Comment by bhupender-isgec** [comment]
Dear,

 

Mail Piler tested. Will be made live tomorrow.

 

 

Thanks

Bhupender K Kashyap

 

 

 

 

From: Bhupender K Kashyap <bhupender.kashyap@isgec.co.in> 
Sent: 17 January 2021 14:15
To: 'Isgec/ITIL-Server' <reply@reply.github.com>; 'Isgec/ITIL-Server' <ITIL-Server@noreply.github.com>
Cc: 'Bhupender K Kashyap' <bhupenderkashyap@isgec.co.in>; 'Mention' <mention@noreply.github.com>
Subject: RE: [Isgec/ITIL-Server] New Mail Piler Server Creation Request By Bhupender ji (#8)

 

Piler -5 Configured  - drive mounted , Piler testing underway keeping. 

Mail testing happen yesterday late night with test emails being recorded. Server is under testing phase.

 

Thanks

Bhupender K Kashyap

**Comment by bhupender-isgec** [comment]
Dear Sir,

 

Piler5 is live now on ip 192.9.200.214

 <mailto:dhirendra.singh@isgec.co.in> @'dhirendra.singh@isgec.co.in' please close 

 

Thanks

Bhupender K Kashyap

 

From: Bhupender K Kashyap <bhupender.kashyap@isgec.co.in> 
Sent: 18 January 2021 23:42
To: 'Isgec/ITIL-Server' <reply@reply.github.com>; 'Isgec/ITIL-Server' <ITIL-Server@noreply.github.com>
Cc: 'Bhupender K Kashyap' <bhupenderkashyap@isgec.co.in>; 'Mention' <mention@noreply.github.com>
Subject: RE: [Isgec/ITIL-Server] New Mail Piler Server Creation Request By Bhupender ji (#8)

 

Dear,

 

Mail Piler tested. Will be made live tomorrow.

 

 

Thanks

Bhupender K Kashyap

 

 

 

 

From: Bhupender K Kashyap <bhupender.kashyap@isgec.co.in <mailto:bhupender.kashyap@isgec.co.in> > 
Sent: 17 January 2021 14:15
To: 'Isgec/ITIL-Server' <reply@reply.github.com <mailto:reply@reply.github.com> >; 'Isgec/ITIL-Server' <ITIL-Server@noreply.github.com <mailto:ITIL-Server@noreply.github.com> >
Cc: 'Bhupender K Kashyap' <bhupenderkashyap@isgec.co.in <mailto:bhupenderkashyap@isgec.co.in> >; 'Mention' <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Subject: RE: [Isgec/ITIL-Server] New Mail Piler Server Creation Request By Bhupender ji (#8)

 

Piler -5 Configured  - drive mounted , Piler testing underway keeping. 

Mail testing happen yesterday late night with test emails being recorded. Server is under testing phase.

 

Thanks

Bhupender K Kashyap

**Comment by dhirendra-isgec** [comment]
As confirmed by Bhupender, closing the case now

**Comment by dhirendra-isgec** [comment]
Pl check the IP

**Comment by bhupender-isgec** [comment]
Dear,

 

Kindly read ip as  192.9.200.194

 

Thanks

Bhupender K Kashyap
